<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d62af9cc-2fd0-426a-aced-ab7ca2ea674f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Middleware\**" />
    <EmbeddedResource Remove="Middleware\**" />
    <None Remove="Middleware\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Resend" Version="0.16.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.34.0" />
    <PackageReference Include="WolverineFx.Postgresql" Version="6.34.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniEnv.Domain\MiniEnv.Domain.csproj" />
  </ItemGroup>

</Project>
